In [1]:
#step1 getdata
import pandas as pd

dataset = pd.read_csv('data\horse-colic_data.csv')
testset = pd.read_csv('data\horse-colic_test.csv')

train = dataset.iloc[:, :].values
test = testset.iloc[:, :].values
print(dataset.shape,testset.shape)
dataset.head()

(299, 28) (67, 28)


2  1   530101  38.5     66    28    3  3.1  NaN  2.1  ...    45   8.4  \
0  1.0  1   534817  39.2   88.0  20.0  NaN  NaN  4.0  1.0  ...  50.0  85.0   
1  2.0  1   530334  38.3   40.0  24.0  1.0  1.0  3.0  1.0  ...  33.0   6.7   
2  1.0  9  5290409  39.1  164.0  84.0  4.0  1.0  6.0  2.0  ...  48.0   7.2   
3  2.0  1   530255  37.3  104.0  35.0  NaN  NaN  6.0  2.0  ...  74.0   7.4   
4  2.0  1   528355   NaN    NaN   NaN  2.0  1.0  3.0  1.0  ...   NaN   NaN   

   NaN.4  NaN.5  2.2  2.3  11300  0  0.1  2.4  
0    2.0    2.0    2    2   2208  0    0  3.0  
1    NaN    NaN    1    2      0  0    0  1.0  
2    3.0    5.3    1    1   2208  0    0  2.0  
3    NaN    NaN    2    2   4300  0    0  2.0  
4    NaN    NaN    2    2      0  0    0  1.0  

[5 rows x 28 columns]

In [2]:
for col in dataset.columns:
    missingdata = dataset[col].isna().sum()
    missingpercent = missingdata/len(dataset) *100
    print(f"{col} : {missingdata} - {missingpercent}%")

2 : 1 - 0.33444816053511706%
1 : 0 - 0.0%
530101 : 0 - 0.0%
38.5 : 60 - 20.066889632107024%
66 : 24 - 8.02675585284281%
28 : 58 - 19.39799331103679%
3 : 56 - 18.729096989966553%
3.1 : 69 - 23.076923076923077%
NaN : 46 - 15.384615384615385%
2.1 : 32 - 10.702341137123746%
5 : 55 - 18.394648829431436%
4 : 44 - 14.715719063545151%
4.1 : 56 - 18.729096989966553%
NaN.1 : 103 - 34.448160535117054%
NaN.2 : 105 - 35.11705685618729%
NaN.3 : 246 - 82.2742474916388%
3.2 : 102 - 34.11371237458194%
5.1 : 118 - 39.46488294314381%
45 : 29 - 9.698996655518394%
8.4 : 33 - 11.036789297658862%
NaN.4 : 164 - 54.84949832775919%
NaN.5 : 197 - 65.88628762541806%
2.2 : 0 - 0.0%
2.3 : 0 - 0.0%
11300 : 0 - 0.0%
0 : 0 - 0.0%
0.1 : 0 - 0.0%
2.4 : 1 - 0.33444816053511706%


In [3]:
#step2 missing value
from sklearn.impute import SimpleImputer
import numpy as np
imputer = SimpleImputer(strategy='median', missing_values=np.nan)
imputer.fit(train[:,:])
train[:,:] = imputer.transform(train[:,:])

imputer.fit(test[:,:])
test[:,:] = imputer.transform(test[:,:])


train[0,:]

array([1.00000e+00, 1.00000e+00, 5.34817e+05, 3.92000e+01, 8.80000e+01,
       2.00000e+01, 3.00000e+00, 1.50000e+00, 4.00000e+00, 1.00000e+00,
       3.00000e+00, 4.00000e+00, 2.00000e+00, 2.00000e+00, 1.00000e+00,
       5.00000e+00, 4.00000e+00, 2.00000e+00, 5.00000e+01, 8.50000e+01,
       2.00000e+00, 2.00000e+00, 2.00000e+00, 2.00000e+00, 2.20800e+03,
       0.00000e+00, 0.00000e+00, 3.00000e+00])

In [4]:
ytrain = train[:, 27]
Xtrain = train[:, 0:27]
ytest = test[:, 27]
Xtest = test[:, 0:27]

In [5]:
#step3 feature extraction
import numpy
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_classif
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
from sklearn.decomposition import PCA
from sklearn.ensemble import ExtraTreesClassifier

#1
# For classification: chi2, f_classif, mutual_info_classif
check = SelectKBest(score_func=f_classif, k=5)
fit = check.fit(Xtrain, ytrain)
set_printoptions(precision=5)
print(fit.scores_)
Xtrain = fit.transform(Xtrain)
Xtest = fit.transform(Xtest)
print(Xtrain[0:5,:])

#2
# model = LogisticRegression(solver='lbfgs')
# rfe = RFE(model, 5)
# fit = rfe.fit(Xtrain, ytrain)
# print("Num Features: %d" % fit.n_features_)
# print("Selected Features: %s" % fit.support_)
# print("Feature Ranking: %s" % fit.ranking_)
# Xtrain = train[:, [6,9,10,22,23]]
# Xtest = test[:, [6,9,10,22,23]]

# #3
# from sklearn.decomposition import PCA
# # feature extraction
# pca = PCA(n_components=5)
# fit = pca.fit(Xtrain)
# # summarize components
# print(fit.components_)

#4
# from sklearn.ensemble import ExtraTreesClassifier
# # feature extraction
# model = ExtraTreesClassifier(n_estimators=10)
# model.fit(Xtrain, ytrain)
# # Xtrain = train[:, [0,8,10,18,19]]
# # Xtest = test[:, [0,8,10,18,19]]       
# print(model.feature_importances_)

[ 5.92325  3.38016  3.72394  0.45685 21.03423  0.70311 17.43297 23.25174
 29.48647 15.79734 22.08077 14.88479 19.29765  0.2401   6.8179   3.41959
  6.60065  8.53215 29.8234  23.3252  10.20216  4.25335  3.52712 19.59652
  1.54735  1.51088  0.3337 ]
[[ 1.5  4.   3.  50.  85. ]
 [ 1.   3.   3.  33.   6.7]
 [ 1.   6.   2.  48.   7.2]
 [ 1.5  6.   3.  74.   7.4]
 [ 1.   3.   2.  45.   7.5]]


In [6]:
#step4 scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
Xtrain = sc.fit_transform(Xtrain)
Xtest = sc.fit_transform(Xtest)

# from sklearn import preprocessing
# mm_scaler = preprocessing.MinMaxScaler()
# Xtrain = mm_scaler.fit_transform(Xtrain)
# Xtest = mm_scaler.transform(Xtest)


In [7]:
Xtrain

array([[-0.42085,  0.75498,  0.03982,  0.38615,  2.35848],
       [-0.95404,  0.08314,  0.03982, -1.32958, -0.60282],
       [-0.95404,  2.09867, -0.81069,  0.1843 , -0.58391],
       ...,
       [ 1.17873,  0.75498,  0.89033,  1.3954 , -0.59904],
       [ 1.17873,  0.08314,  0.03982,  0.38615, -0.62929],
       [-0.42085,  0.08314,  0.03982, -1.0268 ,  1.48863]])

In [8]:
# step5 Discretization
import pandas as pd

from sklearn import preprocessing
# endoce : onehot,onehot-dense,ordinal
# strategy{‘uniform’, ‘quantile’, ‘kmeans’}, default=’quantile’
est = preprocessing.KBinsDiscretizer(n_bins=5, encode='ordinal', strategy='uniform', dtype=None)
est.fit(Xtrain)
# for i in range(0,4):
#     print(est.bin_edges_[i])
Xtrain = est.transform(Xtrain)
Xtest = est.transform(Xtest)

# DecisionTree

In [9]:
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0) #Entropy: used to identify the roo
classifier.fit(Xtrain,ytrain)

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [10]:
y_predTree = classifier.predict(Xtest)

In [11]:
from sklearn import metrics

precisionTree = metrics.precision_score(ytest, y_predTree,average="macro")
accuracyTree = metrics.accuracy_score(ytest, y_predTree)
recallTree = metrics.recall_score(ytest, y_predTree,average="macro")
f1Tree = metrics.f1_score(ytest, y_predTree[ ...],average="macro")

print('DecisionTree')
print('precision: ',precisionTree)
print('accuracy: ',accuracyTree)
print('recall: ',recallTree)
print('f1: ',f1Tree)

DecisionTree
precision:  0.5083333333333333
accuracy:  0.6716417910447762
recall:  0.5056146572104019
f1:  0.5055258467023173


# KNN

In [12]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import metrics 

accuracy = []
precision = []
value = 0
bestk = 0

for n in range(1,30,2):
    model = KNeighborsClassifier(n_neighbors=n)
    model.fit(Xtrain, ytrain)
    y_pred = model.predict(Xtest)
    acu = metrics.accuracy_score(ytest, y_pred)
    accuracy.append(acu)
    if (value < acu):
        value = acu
        bestk = n
   
print(accuracy)
print(value)
print(bestk)

[0.6567164179104478, 0.7313432835820896, 0.6716417910447762, 0.746268656716418, 0.7164179104477612, 0.746268656716418, 0.7164179104477612, 0.7164179104477612, 0.7611940298507462, 0.7761194029850746, 0.7611940298507462, 0.7611940298507462, 0.7611940298507462, 0.7611940298507462, 0.7313432835820896]
0.7761194029850746
19


In [13]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import precision_score 

model = KNeighborsClassifier(n_neighbors=bestk)
model.fit(Xtrain, ytrain)
y_predknn = model.predict(Xtest)

In [14]:
precisionKNN = metrics.precision_score(ytest, y_predknn,average="macro")
accuracyKNN = metrics.accuracy_score(ytest, y_predknn)
recallKNN = metrics.recall_score(ytest, y_predknn,average="macro")
f1KNN = metrics.f1_score(ytest, y_predknn[ ...],average="macro")

print('KNN')
print('precision: ',precisionKNN)
print('accuracy: ',accuracyKNN)
print('recall: ',recallKNN)
print('f1: ',f1KNN)

KNN
precision:  0.8089017900338655
accuracy:  0.7761194029850746
recall:  0.568853427895981
f1:  0.5740740740740741


# SVM

In [15]:
from sklearn import svm
from sklearn import metrics 

mode = ['linear', 'poly', 'rbf', 'sigmoid']

accuracy = []
precision = []
temp = 0
step = '0'

for n in mode:
    clf = svm.SVC(kernel=n)
    clf.fit(Xtrain, ytrain)
    y_pred = clf.predict(Xtest)
    acu = metrics.accuracy_score(ytest, y_pred)
    accuracy.append(acu)
    if (temp < acu):
        temp = acu
        step = n
print(accuracy)
print(temp)
print(step)

[0.746268656716418, 0.7910447761194029, 0.746268656716418, 0.47761194029850745]
0.7910447761194029
poly


In [16]:
from sklearn import svm

clf = svm.SVC(kernel=step)
clf.fit(Xtrain, ytrain)
y_predsvm = clf.predict(Xtest)

In [17]:
precisionSVM = metrics.precision_score(ytest, y_predsvm,average="macro")
accuracySVM = metrics.accuracy_score(ytest, y_predsvm)
recallSVM = metrics.recall_score(ytest, y_predsvm,average="macro")
f1SVM = metrics.f1_score(ytest, y_predsvm[ ...],average="macro")

print('SVM')
print('precision: ',precisionSVM)
print('accuracy: ',accuracySVM)
print('recall: ',recallSVM)
print('f1: ',f1SVM)

SVM
precision:  0.8141025641025642
accuracy:  0.7910447761194029
recall:  0.6105200945626478
f1:  0.6362289562289561


# SUMARY

In [18]:
print('DecisionTree')
print('precision: ',precisionTree)
print('accuracy: ',accuracyTree)
print('recall: ',recallTree)
print('f1: ',f1Tree)

print('KNN')
print('precision: ',precisionKNN)
print('accuracy: ',accuracyKNN)
print('recall: ',recallKNN)
print('f1: ',f1KNN)

print('SVM')
print('precision: ',precisionSVM)
print('accuracy: ',accuracySVM)
print('recall: ',recallSVM)
print('f1: ',f1SVM)

DecisionTree
precision:  0.5083333333333333
accuracy:  0.6716417910447762
recall:  0.5056146572104019
f1:  0.5055258467023173
KNN
precision:  0.8089017900338655
accuracy:  0.7761194029850746
recall:  0.568853427895981
f1:  0.5740740740740741
SVM
precision:  0.8141025641025642
accuracy:  0.7910447761194029
recall:  0.6105200945626478
f1:  0.6362289562289561


In [19]:
from sklearn.model_selection import cross_val_score
X = np.append(Xtrain[:, :] , Xtest[:, :],axis=0)
y = np.append(ytrain , ytest)
scores = cross_val_score(model, X, y, cv=5)
print('Tree: ',cross_val_score(classifier, X, y, cv=5))
print('knn: ',cross_val_score(model, X, y, cv=5))
print('SVM: ',cross_val_score(clf, X, y, cv=5))

Tree:  [0.64865 0.61644 0.57534 0.68493 0.71233]
knn:  [0.62162 0.68493 0.75342 0.64384 0.67123]
SVM:  [0.66216 0.65753 0.79452 0.65753 0.71233]
